name: Build and Release Monorepo

on:
  push:
    branches:
      - main
  issue_comment:
    types:
      - created
      - edited

env:
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  beta-release:
    if: github.event_name == 'issue_comment' && github.event.comment.body == '/release-beta'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Enable Corepack and Set Yarn Version
        run: |
          corepack enable
          corepack prepare yarn@4.3.1 --activate

      - name: Install Dependencies
        run: yarn install

      - name: Make handle-release.sh Executable
        run: chmod +x scripts/handle-release.sh

      - name: Run Beta Release Script
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ./scripts/handle-release.sh beta

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Enable Corepack and Set Yarn Version
        run: |
          corepack enable
          corepack prepare yarn@4.3.1 --activate

      - name: Install Dependencies
        run: yarn install

      - name: Make handle-release.sh Executable
        run: chmod +x scripts/handle-release.sh

      - name: Run Custom Release Script
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ./scripts/handle-release.sh
